version: '3.8'

services:
  marktmakr-dev:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    volumes:
      - ..:/home/build/app:cached
    environment:
      - POSTGRES_HOST=localhost
      - NODE_ENV=dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - API_PORT=3000
      - MAKER_PORT=4200
      - STORE_PORT=4201
    command: sleep infinity
    depends_on:
      - postgres
      - pgadmin

  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin5
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:
