version: '3.8'

services:
  marktmakr-dev:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    volumes:
      - ..:/home/build/app:cached
    environment:
      - POSTGRES_HOST=postgres
      - NODE_ENV=dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PORT=5432
      - API_PORT=3000
      - MAKER_PORT=4200
      - STORE_PORT=4201
    command: sleep infinity
    depends_on:
      - postgres
      - pgadmin
    links:
      - postgres
      - pgadmin
    networks:
      - postgres

  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - '8888:80'
    expose:
      - 8888
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin4
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
